// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tctfcwjueadnqoyyeovf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdGZjd2p1ZWFkbnFveXllb3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDQ5MjYsImV4cCI6MjA2NjkyMDkyNn0.kJOjFgI99vNBzyCVaIvuuIVfIPSHTG6WiRByo984vjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});